version: '3.1'

services:

  adminer:
    image: arm64v8/phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8080:80

  db:
    image: arm64v8/mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
  
  php:
    image: arm64v8/php:7.4-apache
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html

volumes:
  db:
